### ISSUE TITLE
Monthly view failure to load

### ISSUE THREAD

**Issue by gregemuze** [timbaobjects/birthregistration#11]
The "Monthly" view doesn't load up the year to date cumulative report as it should.

We should also change the label to "YTD" for better descriptiveness.

**Comment by dodumosu** [comment]
After reviewing with @gregemuze, it was decided to remove the "Monthly" button, since clicking on the current year does what is required.

**Comment by takinbo** [comment]
Not certain if I agree with that. If that were the case, the issue would not have occurred in the first place. We should discuss this again.
